stanford_basic.settings:
  type: theme_settings
  label: 'Stanford Basic theme settings'
  mapping:
    browser_sync:
      type: mapping
      label: 'Enable Browser Sync'
      mapping:
        enabled:
          type: boolean
          label: 'Enable Browser Sync'
        host:
          type: string
          label: 'Host'
        port:
          type: integer
          label: 'Port'
    clear_registry:
      type: boolean
      label: 'Enable clear Registry'
    ie_enabled:
      type: boolean
      label: 'Enable IE support HTML classes'
    ie_enabled_versions:
      type: mapping
      label: 'IE versions supported'
      mapping:
        ie8:
          type: boolean
          label: 'Support IE8'
        ie9:
          type: boolean
          label: 'Support IE8'
